### PR TITLE
Changed datalayer call from array to object

### PR DESCRIPTION
**Pull request by Auz**

### CODE REVIEW

**Comment by vexersa** [comment]
I was hoping for an update on this fix 🙏a

**Comment by Auz** [comment]
We have another PR in the works that will fix this in a more complete way. It should be live this week. I'll link the PR once it's published.

**Comment by vexersa** [comment]
Great news

**Comment by Auz** [comment]
This is fixed in [2210](https://github.com/growthbook/growthbook/pull/2210)

**Pull request closed without merging**
