### PR TITLE
Fix esm exports

### LINKED ISSUE #509: sdk-js/package.json: "type": "module"
As per: https://www.linen.dev/s/growthbookusers/t/442993/Hi-guys-I-m-having-some-package-module-issues-using-the-SDK-

>When adding “type” : “module” I still got errors
>
>```
>node:internal/errors:466
>  ErrorCaptureStackTrace(err);
>  ^
>
>Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/xxx/node_modules/@growthbook/growthbook/dist/esm/GrowthBook' imported from /Users/xxx/node_modules/@growthbook/growthbook/dist/esm/index.js
>```
>
>However, when I started checking that code, I saw that `.js` was missing from the import path in the following places:
>
>`node_modules/@growthbook/growthbook/dist/esm/index.js` -> missing in `export { GrowthBook } from "./GrowthBook";`
>`node_modules/@growthbook/growthbook/dist/esm/GrowthBook.js` -> missing in `util` and `mongrule` import
>
>By adding .js to those three places (combined with adding `"type" : "module"` to package.json) it started up just fine!

Took a quick look at [packages/sdk-js](https://github.com/growthbook/growthbook/tree/b9232c4/packages/sdk-js) & [the history for packages/sdk-js](https://github.com/growthbook/growthbook/commits/b9232c4/packages/sdk-js) and it looks like these changes haven't landed yet, also checked PRs and didn't see one that looked like a match.

### PR DESCRIPTION
**Pull request by ken-browning**
Fixes #509

### Features and Changes

1. Files in `dist/esm` have had their extensions changed from .js to .mjs. This is a requirement to load the files as ESM when the package.json does not include `"type": "module"`.
2. The package.json references to files in `dist/esm` have been updated accordingly.
3. The relative imports inside of `dist/esm` have been updated to include a file extension.

- Closes **#509**

### Testing

 I tested with this locally
 ```
diff --git a/packages/sdk-js-esm-consumer/index.cjs b/packages/sdk-js-esm-consumer/index.cjs
new file mode 100644
index 00000000..dd74bc2b
--- /dev/null
+++ b/packages/sdk-js-esm-consumer/index.cjs
@@ -0,0 +1,3 @@
+const assert = require("node:assert");
+const { GrowthBook } = require("@growthbook/growthbook");
+assert(typeof GrowthBook === "function");
diff --git a/packages/sdk-js-esm-consumer/index.mjs b/packages/sdk-js-esm-consumer/index.mjs
new file mode 100644
index 00000000..27474bba
--- /dev/null
+++ b/packages/sdk-js-esm-consumer/index.mjs
@@ -0,0 +1,3 @@
+import assert from "node:assert";
+import { GrowthBook } from "@growthbook/growthbook";
+assert(typeof GrowthBook === "function");
diff --git a/packages/sdk-js-esm-consumer/package.json b/packages/sdk-js-esm-consumer/package.json
new file mode 100644
index 00000000..a42460e4
--- /dev/null
+++ b/packages/sdk-js-esm-consumer/package.json
@@ -0,0 +1,8 @@
+{
+  "name": "sdk-js-esm-consumer",
+  "version": "1.0.0",
+  "type": "module",
+  "dependencies": {
+    "@growthbook/growthbook": "^0.29.0"
+  }
+}
```

### CODE REVIEW

**Comment by bttf** [comment]
Hi @ken-browning , this looks mostly good. You have a couple merge conflicts - they should both accept changes from upstream. Also, it seems that your `yarn.lock` changes include several modules that aren't necessary

**Comment by ken-browning** [comment]
@bttf I have rebased

**Comment by august-growthbook** [comment]
Hi @bttf could you kindly take another look at this PR? This fixes a blocker for one of our paying customers. Thank you!

**Comment by bttf** [comment]
Hi @ken-browning Thanks, we need some time to make sure we're not breaking anything here

**Comment by benmccann** [comment]
Hi, SvelteKit maintainer and Vite contributor here. I have a lot of experience with packages encountering these types of errors and would like to weigh in to say that this is the correct fix and I don't see anything here that would break under any of the various bundlers or runtimes.

There's a great tool called publint, which you can use to check if you've packaged your library correctly: https://publint.dev/@growthbook/growthbook@1.0.0

**Comment by jdorn** [comment]
Thanks for the work here and sorry for the long delay on this PR.  I wanted to test this with a number of different bundlers/runtimes to ensure we weren't introducing any breaking changes.  I successfully tested with Node (cjs + esm), Astro, Next.js, Remix, and Svelte.

**Pull request merged**
