### PR TITLE
Imports cleanup

### PR DESCRIPTION
**Pull request by bttf**
Changes around imports; I was doing some refactoring and found myself having to count how many `../../` I needed to type ... Not anymore

This is my first crack at it and definitely open to suggestions on refining this

### Changes: Backend and Frontend
- Applying `import/order` eslint rule. This is to help keep our import statements in a sane order and will report an eslint error if they aren't. Luckily it's something eslint can autofix. The order configured in this PR:
  - built-in modules
  - external modules
  - internal modules
  - parent/sibling imports
  - everything else

### Changes: Only on the Frontend
- Because Next.js supports tsconfig `paths` aliases out of the box, I have updated `packages/front-end/tsconfig.json` with a paths alias of `@/` to alias the root dir of front-end. This will allow us to refer to project directories with absolute paths. For example, `../../services/utils` becomes `@/services/utils`
- I ran a codemod to transform the code. Can publish that script in a separate gist later
- Open to suggestions on alias naming. I opted for `@/` because without it it may be hard to notice at a glance which imports are external libraries and which are ours

I only applied the path aliasing changes to the frontend because it would require a little more work on the backend, including a change in how we boot the production node app. I would like to socialize these changes first and make sure we iron out the kinks before making the more precarious change on the backend.

### CODE REVIEW

**Comment by bryce-fitzsimons** [comment]
@bttf Thinking we should hold off on this merge until after after we work through most of the other bug day PRs, as this might cause a lot of merge conflicts.

**Comment by bttf** [comment]
> @bttf Thinking we should hold off on this merge until after after we work through most of the other bug day PRs, as this might cause a lot of merge conflicts on those PRs.

That's fair

**Comment by bttf** [comment]
Codeshift script: https://gist.github.com/bttf/afc83ce9fd9f8a259c01d71f4750aa1a

I updated the codeshift so that we keep single-level parent imports (`../`) around, as well as sibling imports (`./`), for convenience's sake.

There is no eslint rule to enforce that we keep our import paths to this convention - it would require writing a custom one. I don't think we need it but can look into it if others feel it's necessary.

**Comment by jdorn** [comment]
I'm having trouble getting this to play nicely with VS Code.  On save, it's changing the order of imports and it doesn't like the `@/` alias.

**Comment by bttf** [comment]
> I'm having trouble getting this to play nicely with VS Code. On save, it's changing the order of imports and it doesn't like the `@/` alias.

Interesting. Is it possible that you have a local prettier configuration (or something similar) that is enforcing import ordering?  I'm testing it in VS Code on my side and am not seeing it happening.

As for the `@/` alias, it could be that your local typescript server just needs some time to acclimate to the change. The resolution of these paths in VS Code's autocomplete for example is based on the local TS language server. When I opened up VS Code for the first time, I had to wait for my TS server to initialize before it recognized the alias paths.

**Review by jdorn — APPROVED** [review]

**Pull request merged**
