### PR TITLE
Change trigger for non-main branches from push to pull_request

### PR DESCRIPTION
**Pull request by bttf**
Changes to `ci` workflow:
- Change event trigger from `push` to `pull_request`
  - Triggering on `push` "will build on the main branch and any feature branch, even without a PR." ([ref](https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/ci-cd/github-actions/triggers.html))
  - I don't think we want to do this, but instead only on `pull_request` events (opened, sync'd, reopened).
- Add `push` event trigger for `main` branch only

Effectively, the above changes mean:
- We only run CI for branches that **have a pull request**
- We run CI for **every push event** made to `main` branch only

This seems to fix the 'CI not running for contributors' problem (tested [here](https://github.com/growthbook/growthbook/pull/1490)). I'm not sure why, there are no docs explaining this (-1 GitHub Actions).

What pointed me to this was the fact that our preview environments were running just fine for contributor PRs. The only discrepancy I could find were the event triggers: `push` vs `pull_request`

### CODE REVIEW

**Comment by tinahollygb** [comment]
Couple of questions/concerns with this approach:

1. We used to have it on pull_request, and previously on push. If I read through the history of this file, it looks like we keep flip flopping back and forth. Using both triggers seems fine to me, but I'd like to understand more about why we kept switching, and maybe we're missing some context, but I'm ok with both. ✅ 
2. Does this solve the concern that @jdorn had where the secrets could be exposed if a user changes the `ci.yml` file? With the workflow_dispatch trigger, Github is very explicit that only the workflows on the trunk branch will run when the trigger is activated. It is, however, ambiguous if our workflows run or if theirs do, and where they run, e.g. do they use our runners and our environment secrets, or the contributor's? I would assume ours and our secrets, but it would seem like a glaring security oversight from Github if contributors were allowed to modify the workflows that run. So, I'd like to confirm: the workflows that run, which `ci.yml` file do they use: the one on the trunk (like workflow_dispatch triggers) or the one in the contributed patch?

**Comment by bttf** [comment]
> Couple of questions/concerns with this approach:
> 
> 1. We used to have it on pull_request, and previously on push. If I read through the history of this file, it looks like we keep flip flopping back and forth. Using both triggers seems fine to me, but I'd like to understand more about why we kept switching, and maybe we're missing some context, but I'm ok with both. ✅
> 2. Does this solve the concern that @jdorn had where the secrets could be exposed if a user changes the `ci.yml` file? With the workflow_dispatch trigger, Github is very explicit that only the workflows on the trunk branch will run when the trigger is activated. It is, however, ambiguous if our workflows run or if theirs do, and where they run, e.g. do they use our runners and our environment secrets, or the contributor's? I would assume ours and our secrets, but it would seem like a glaring security oversight from Github if contributors were allowed to modify the workflows that run. So, I'd like to confirm: the workflows that run, which `ci.yml` file do they use: the one on the trunk (like workflow_dispatch triggers) or the one in the contributed patch?

1. I think we were trying to address an issue before (CI not running for `main`) and in the process of that, introduced another bug (CI not running for public PRs). Adding both now addresses both situations - we watch for `push` events on `main` only, and for `pull_request` events for feature branches, which allows us to run CI for contributor branches
2. Your concern if valid. This is why there is an 'Approve and Run' step for PRs from outside the org. To answer your question
  i. They run the `ci.yml` in the branch, not in trunk
  ii. It's up to **us** to confirm that they have not edited these files
  iii. Nothing runs before a maintainer clicks 'Approve and Run'. This is why we need to confirm there were no changes before approving and running.

I've basically summarized [GitHub's documentation on this exact concern](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork).

> Inspect the proposed changes in the pull request and ensure that you are comfortable running your workflows on the pull request branch. You should be especially alert to any proposed changes in the .github/workflows/ directory that affect workflow files.

**Review by jdorn — APPROVED** [review]
I'm not sure I understand why this change would fix anything, but it looks harmless to me

**Comment by bttf** [comment]
> > I think we were trying to address an issue before (CI not running for main) and in the process of that
> 
> This change also allowed us to run the workflows on push to our feature branches, so we would know earlier than when we create a PR that CI was broken. I think it was also an effort to prevent everyone opening blank draft PR's to see CI running (which pings everyone watching the repo).

Right, that is true but it wasn't really the intention (I made the change last time). The CI job is essentially running `yarn lint`, `yarn type-check`, and `yarn test`, which we all can and should be running locally anyway. (No reason to utilize cloud resources to do this.)

> @bttf regarding the 2nd concern, what happens in this case:
> 
> 1. User submits an OK PR
> 2. We click approve and run to run the workflow
> 3. User updates the ci.yml file
> 
> Will the updated workflows run because they have already been approved? Or do they need to be re-approved?

This is a good question. I couldn't find anything in the GitHub docs. I've posted a question on their support form [here](https://github.com/orgs/community/discussions/61672). Regardless, this is a flow that isn't introduced with these changes nor changed so we're technically dealing with this today. I don't consider it a blocker but definitely worth knowing for sure.

**Pull request merged**
