### PR TITLE
bugfix: fix RepositoryKey type typo

### PR DESCRIPTION
**Pull request by Hephaest**
### Features and Changes

This bugfix is for issue #1430 

### Dependencies

No dependencies needed

### Testing

1. deploy this branch to npm
2. install the package
3. import this package into your project and run `yarn start`

### Result
No compilation error

### CODE REVIEW

**Comment by Hephaest** [comment]
Hi @Auz , @epugh, @jacobwgillespie and @Angelbear 

Please help review this PR, thanks! ❤️

**Comment by jacobwgillespie** [comment]
(I'm not actually affiliated with GrowthBook)

Those types aren't equivalent - before your change, it requires that the input string contain the string `||`. Technically TypeScript would allow any string where it contains at least `||`, though the type definition implies that there must be something before and after the `||`. See [this example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAgmCWAJA9gZ2FAvFdAneAdgOYBQokUAwgDbwQHADSEIWOw+xZ40AShGDTxgyXCGatsAAwAkAbzhI0wAL4AfNfJp0GElVJIkAZgFcCAY2DxkBKMAjoAFITAngALij9BqYaPEsAJRQciqG9k4A5MAAFvCoGgDuogDWqJGBZA7AjtFxCWoZWVFJqemZETmRGkXFVTEQ1NTIRZW5ybjUACZFQA) in the TypeScript playground. TypeScript calls this type a [template literal type](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

I believe the fix for your issue #1430 is to upgrade your version of TypeScript. TypeScript 3.8 is over three years old now. TypeScript 4.1 introduced template literal types in November 2020.

**Comment by Hephaest** [comment]
Hi @jacobwgillespie , thanks for your kind reply! I do know the issue can be fixed by a TypeScript upgrade. But honestly, this is a challenging decision for an old project (Yes, it is not my own project). I believe there are other GrowthBook lovers who use pretty old projects but would like to give it a try. The key point here is about back compatibility. 🤔

**Comment by jdorn** [comment]
We can consider making this change.  That specific type `RepositoryKey` is only used internally in the SDK and we're only constructing the string in one place.  So the risk of typos caused by a relaxed type def is pretty small and likely outweighed by better backwards compatibility.

I don't want to commit to supporting old Typescript versions forever, but in this case the change is minor.

**Review by yangyang198703 — APPROVED** [review]

**Comment by Hephaest** [comment]
Hi @tinahollygb, could you help merge this PR? ❤️

**Comment by jdorn** [comment]
This was fixed as part of adding Remote Eval in #1677

**Pull request closed without merging**
