### PR TITLE
Upgrade mongodb to 4.14.

### PR DESCRIPTION
**Pull request by ianb-pomelo**
### Features and Changes

mongodb 4 is required to connect to Mongo Atlas (https://www.mongodb.com/atlas/database). There were several breaking changes to go from 4 to 5 so just did a single major version upgrade. Also upgraded mongoose to 6.10.

The largest change is adding types to the Mongoose document generics and explicitly setting `{ flattenMaps: true }` for all document -> json conversion. It also unsets some values in the mongoose connection that are now the default values.

See https://mongoosejs.com/docs/6.x/docs/api/document.html#document_Document-toJSON

- Closes **#935**

### Testing

Ensure that the backend can still correctly connect to Mongo and that basic reads and writes work.

### CODE REVIEW

**Comment by ianb-pomelo** [comment]
Would love a look at this when you get a chance!

**Comment by tinahollygb** [comment]
Just adding a note here after talking to your colleague Tommy there's possibly a bug in this related to the removal of the `.toJSON()` in the `toInterface()` method of the feature model changes which is impacting how objects are copied. Cannot confirm as I did not run this fork, but I cannot recommend merging this as is at this time. 

The contributed logic changes from returning the JSON object to returning the document directly from Mongoose/Mongo, which may have some side effects as there's currently a bug being experienced with data not being copied properly with this fork which may be related to a resulting `FeatureInterface` not being copied.

**Comment by ianb-pomelo** [comment]
Thanks for the feedback! I've updated this to still use `toJSON()` which works now with a typed document and not flattening the maps. Hopefully this should work but it's a bit hard to test

**Comment by tinahollygb** [comment]
> Hopefully this should work but it's a bit hard to test

These changes have created some [issues](https://github.com/growthbook/growthbook/pull/1049#issuecomment-1555356881) on your instance, have you confirmed those issues no longer occur? That's one way to test the side effects of your changes. You can talk to your colleague Tommy about the failing code paths that should be tested. 

Either way, I think this makes sense as something we handle internally—the omission of `.toJSON()` is a pretty big oversight, so I'm worried there may be other oversights that have not been caught. We will work on this internally, though I'll reference this work if needed.

**Pull request closed without merging**
