### PR TITLE
Resolve missing types in TypeScript 5

### PR DESCRIPTION
**Pull request by leachtucker**
### Features and Changes

- Resolves missing type declarations error in TypeScript 5 projects with `moduleResolution` set to `bundler`

### Screenshots

The resolved TS Error:
TS Error

### CODE REVIEW

**Comment by bttf** [comment]
Hi @leachtucker Could you specify which bundler you are using?

**Comment by leachtucker** [comment]
Hey @bttf, we are using Vite. Although, this issue is not specific to Vite -- it occurs for any TS projects utilizing the new `bundler` option as its moduleResolution

**Comment by bttf** [comment]
Hi @leachtucker Thanks for your patience. I was able to repro and the changes look good on my end. Will merge by EOD

**Comment by leachtucker** [comment]
> Hi @leachtucker Thanks for your patience. I was able to repro and the changes look good on my end. Will merge by EOD

Hey @bttf. That sounds good! Thank you 🙂

**Review by bttf — APPROVED** [review]

**Comment by chambo-e** [comment]
Hello @bttf 👋 

Would it be possible to release a new version of the packages to include this fix please ? 

Thanks :)

**Pull request merged**
