### PR TITLE
Enable multiple page visual experiments

### PR DESCRIPTION
**Pull request by bryce-fitzsimons**
### Features and Changes

Just unlocks the pre-existing multi-page visual changeset functionality in the UI

### Screenshots

image

### CODE REVIEW

**Comment by bttf** [comment]
Looks good, just one minor suggestion - perhaps we could use additional labeling like 'Page #1', 'Page #2'?

**Comment by bryce-fitzsimons** [comment]
> Looks good, just one minor suggestion - perhaps we could use additional labeling like 'Page #1', 'Page #2'?

I thought about that, and also using the editorUrl as headers. But not sure if I love either. The ordering / page # is arbitrary and carries no meaning. And the editorUrl is awkward as it might not change from page to page.

**Comment by jdorn** [comment]
Visually, it kinds of runs together.  I think wrapping each changeset in `<div className="appbox bg-light p-3 mb-3"></div>` would help a lot.

**Comment by tinahollygb** [comment]
Minor branding-related concern, I just took a look at the screenshot, are these colours new? I don't see them added in this PR but they don't look like they match the rest of the app, mainly the yellow, turquoise, and indigo/perrywinkle blue.

image

The yellow is a bit jarring. How does it look in dark mode?

**Pull request merged**
