### PR TITLE
[Feat] Sticky column headers for features list (#1454)

### LINKED ISSUE #1454: [Feature] Sticky column headers for features list
Right now, if you have a lot of features on the feature listing page, when you scroll, you lose the context for the column names. It would be good to have the column names be sticky.

### PR DESCRIPTION
**Pull request by Satyam-G5**
### Features and Changes

- Made the position of column headers in the features list sticky.
- When more than 7 features are added, the column names are scrollable and can now be seen even when overlapped by the navbar.
- Applied CSS changes to packages/front-end/pages/features/index.tsx to make the column headers sticky just before the navbar.

Fixes #1454

- Closes **https://github.com/growthbook/growthbook/issues/1454**

### Dependencies
None 

### Testing

To test these changes, follow these steps:
1. Go to the homepage.
2. Add a project.
3. Navigate to the "Features" section from the left-hand side.
4. Add 8 or more features.
5. Scroll down and observe that the column headers remain sticky.
6. Screenshots have been included to provide visual documentation for this pull request.

### Screenshots

when adding more features :
Screenshot 2023-07-18 052415
after scrolling : 
Screenshot 2023-07-18 052448

### CODE REVIEW

**Comment by tinahollygb** [comment]
Nice! How does it look on mobile? Can you also share what it looks like without the shadow for both desktop and mobile?

**Comment by Satyam-G5** [comment]
Hi @tinahollygb , sure here's the mobile view for the above 
:


Screenshot 2023-07-19 040010
# after scrolling :
Screenshot 2023-07-19 040031

**Comment by Satyam-G5** [comment]
I would suggest to keep shadow as it provide a better UI , here's how it look like without shadow 
:
Screenshot 2023-07-19 040218

# in mobile : 
Screenshot 2023-07-19 041149

**Review by tinahollygb — APPROVED** [review]
Looks great!

**Pull request merged**
