### PR TITLE
Update url-redirects.mdx

### PR DESCRIPTION
**Pull request by august-growthbook**
### Features and Changes

Added a blurb about making sure the SDK Connection allows URL Redirect tests.

### CODE REVIEW

**Review by msamper — APPROVED** [review]
Thanks for this update!

**Comment by royalfig** [comment]
@august-growthbook This is great. I tried to rework some of the language to be a bit more explicit. I was a little confused of where I was supposed to go. If this looks, we can merge.

**Comment by august-growthbook** [comment]
Thanks Ryan. It should be SDK Connections --> Select the relevant SDK Connection --> Click the "Edit" button. The edited version left out the middle step.

**Comment by royalfig** [comment]
@august-growthbook Thanks! Added missing step.

**Pull request merged**
